# -*- coding: utf-8 -*-
"""practical3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIs1f4JipIcWJXeGJgU2CYK2gjWKPIS5
"""

import math
import numpy as np

name = input("Enter student name: ")

n = int(input("Enter number of courses: "))

marks = []
credits = []

for i in range(n):
    mark = float(input(f"Enter mark {i + 1}: "))
    credit = int(input(f"Enter credit {i + 1}: "))

    mark = math.floor(mark * 10) / 10

    marks.append(mark)
    credits.append(credit)

marks = np.array(marks)
credits = np.array(credits)

gpa = np.sum(marks * credits) / np.sum(credits)

print("\nStudent:", name)
print("Marks:", marks)
print("GPA:", round(gpa, 2))