# -*- coding: utf-8 -*-
"""practical4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtR5sTS90-T0vZH-JQaPEAZbIkpVgbGB
"""

import numpy as np


class Student:
    def __init__(self, name, marks, credits):
        self.name = name
        self.marks = np.array(marks)
        self.credits = np.array(credits)

    def floor_marks(self):
        self.marks = np.floor(self.marks * 10) / 10

    def calculate_gpa(self):
        return np.sum(self.marks * self.credits) / np.sum(self.credits)



class Course:
    def __init__(self, name, credit):
        self.name = name
        self.credit = credit

    def __str__(self):
        return f"{self.name} - {self.credit} credits"


# ---------- domains/__init__.py ----------

from .student import Student
from .course import Course



from domains import Student


def input_student():
    name = input("Enter student name: ")
    n = int(input("Enter number of courses: "))

    marks = []
    credits = []

    for i in range(n):
        mark = float(input(f"Enter mark {i + 1}: "))
        credit = int(input(f"Enter credit {i + 1}: "))

        marks.append(mark)
        credits.append(credit)

    student = Student(name, marks, credits)
    student.floor_marks()

    return student


def display_student(student):
    print("\nStudent:", student.name)
    print("Marks:", student.marks)
    print("GPA:", round(student.calculate_gpa(), 2))


def display_courses(courses):
    print("\nCourses:")

    for course in courses:
        print(course)



from input import input_student
from output import display_student, display_courses
from domains import Course


def main():
    student = input_student()

    display_student(student)

    courses = []

    n = int(input("\nEnter number of courses to display: "))

    for i in range(n):
        name = input(f"Enter course {i + 1} name: ")
        credit = int(input(f"Enter course {i + 1} credit: "))

        courses.append(Course(name, credit))

    display_courses(courses)


if __name__ == "__main__":
    main()